name: Build Python Script as Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyperclip

    - name: Build the executable
      run: pyinstaller --onefile --noconsole tag_formatter.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-file
        path: dist/tag_formatter.exe
